language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo clean && hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: sources
  target_branch: master
  local-dir: public
