language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branch: source # build source branch only
script:
  - hexo generate && hexo deploy
deploy:
  provider: pages
  cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  on:
    branch: source
  local_dir: public/
