language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    repo: leostudiooo/leostudiooo.github.io
    branches:    # ← new!
      only:      # ← new!
        - master # ← new!
  local_dir: public