/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/b707o/': RouteRecordInfo<
      '/b707o/',
      '/b707o',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bullshit-talker/': RouteRecordInfo<
      '/bullshit-talker/',
      '/bullshit-talker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/pomodoro/README': RouteRecordInfo<
      '/pomodoro/README',
      '/pomodoro/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/传送带问题及解决策略': RouteRecordInfo<
      '/posts/传送带问题及解决策略',
      '/posts/%E4%BC%A0%E9%80%81%E5%B8%A6%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3%E7%AD%96%E7%95%A5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/常见的追击相遇问题及解决策略': RouteRecordInfo<
      '/posts/常见的追击相遇问题及解决策略',
      '/posts/%E5%B8%B8%E8%A7%81%E7%9A%84%E8%BF%BD%E5%87%BB%E7%9B%B8%E9%81%87%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3%E7%AD%96%E7%95%A5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/运动学': RouteRecordInfo<
      '/posts/运动学',
      '/posts/%E8%BF%90%E5%8A%A8%E5%AD%A6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/9-000-Man-made-Things-Flying-in-Space': RouteRecordInfo<
      '/posts/9-000-Man-made-Things-Flying-in-Space',
      '/posts/9-000-Man-made-Things-Flying-in-Space',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai-painting': RouteRecordInfo<
      '/posts/ai-painting',
      '/posts/ai-painting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/album-stars': RouteRecordInfo<
      '/posts/album-stars',
      '/posts/album-stars',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/apple-love-and-hate-s': RouteRecordInfo<
      '/posts/apple-love-and-hate-s',
      '/posts/apple-love-and-hate-s',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/biochemistry-i': RouteRecordInfo<
      '/posts/biochemistry-i',
      '/posts/biochemistry-i',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blind-jb-write-sept-1': RouteRecordInfo<
      '/posts/blind-jb-write-sept-1',
      '/posts/blind-jb-write-sept-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/casio-999-01': RouteRecordInfo<
      '/posts/casio-999-01',
      '/posts/casio-999-01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/casio-999-02': RouteRecordInfo<
      '/posts/casio-999-02',
      '/posts/casio-999-02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/casio-999-03': RouteRecordInfo<
      '/posts/casio-999-03',
      '/posts/casio-999-03',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/celebrate': RouteRecordInfo<
      '/posts/celebrate',
      '/posts/celebrate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/doppler-effect': RouteRecordInfo<
      '/posts/doppler-effect',
      '/posts/doppler-effect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways': RouteRecordInfo<
      '/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways',
      '/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hexo': RouteRecordInfo<
      '/posts/hexo',
      '/posts/hexo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/how-to-make-an-open-source-dial': RouteRecordInfo<
      '/posts/how-to-make-an-open-source-dial',
      '/posts/how-to-make-an-open-source-dial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/memo-protein-folding': RouteRecordInfo<
      '/posts/memo-protein-folding',
      '/posts/memo-protein-folding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/openjudge-7940': RouteRecordInfo<
      '/posts/openjudge-7940',
      '/posts/openjudge-7940',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/penguinplayer': RouteRecordInfo<
      '/posts/penguinplayer',
      '/posts/penguinplayer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/phys-note-2122-t1w2': RouteRecordInfo<
      '/posts/phys-note-2122-t1w2',
      '/posts/phys-note-2122-t1w2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/raspberry-pi-cups-wireless-printer': RouteRecordInfo<
      '/posts/raspberry-pi-cups-wireless-printer',
      '/posts/raspberry-pi-cups-wireless-printer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/smartphone-sensor-magfield': RouteRecordInfo<
      '/posts/smartphone-sensor-magfield',
      '/posts/smartphone-sensor-magfield',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/the-way-of-university': RouteRecordInfo<
      '/posts/the-way-of-university',
      '/posts/the-way-of-university',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tijie-p1085': RouteRecordInfo<
      '/posts/tijie-p1085',
      '/posts/tijie-p1085',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tijie-p4414': RouteRecordInfo<
      '/posts/tijie-p4414',
      '/posts/tijie-p4414',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tijie-p5716': RouteRecordInfo<
      '/posts/tijie-p5716',
      '/posts/tijie-p5716',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/travel-lights': RouteRecordInfo<
      '/posts/travel-lights',
      '/posts/travel-lights',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vscode-cpp': RouteRecordInfo<
      '/posts/vscode-cpp',
      '/posts/vscode-cpp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wechat-miniapp-token': RouteRecordInfo<
      '/posts/wechat-miniapp-token',
      '/posts/wechat-miniapp-token',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/when-a-shoeshine-boy-starts-to-cultivate-lobsters': RouteRecordInfo<
      '/posts/when-a-shoeshine-boy-starts-to-cultivate-lobsters',
      '/posts/when-a-shoeshine-boy-starts-to-cultivate-lobsters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wintervacation-plan': RouteRecordInfo<
      '/posts/wintervacation-plan',
      '/posts/wintervacation-plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yun': RouteRecordInfo<
      '/posts/yun',
      '/posts/yun',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/random/': RouteRecordInfo<
      '/random/',
      '/random',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.30_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser@7.29.0_@nuxt+kit@3.21.1_@types+markdown-it@14.1.2_@types+no_3ce8d468719cfd71f707f76025cec41f/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/b707o/index.md': {
      routes:
        | '/b707o/'
      views:
        | never
    }
    'pages/bullshit-talker/index.md': {
      routes:
        | '/bullshit-talker/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.30_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'pages/pomodoro/README.md': {
      routes:
        | '/pomodoro/README'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.30_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/传送带问题及解决策略.md': {
      routes:
        | '/posts/传送带问题及解决策略'
      views:
        | never
    }
    'pages/posts/常见的追击相遇问题及解决策略.md': {
      routes:
        | '/posts/常见的追击相遇问题及解决策略'
      views:
        | never
    }
    'pages/posts/运动学.md': {
      routes:
        | '/posts/运动学'
      views:
        | never
    }
    'pages/posts/9-000-Man-made-Things-Flying-in-Space.md': {
      routes:
        | '/posts/9-000-Man-made-Things-Flying-in-Space'
      views:
        | never
    }
    'pages/posts/ai-painting.md': {
      routes:
        | '/posts/ai-painting'
      views:
        | never
    }
    'pages/posts/album-stars.md': {
      routes:
        | '/posts/album-stars'
      views:
        | never
    }
    'pages/posts/apple-love-and-hate-s.md': {
      routes:
        | '/posts/apple-love-and-hate-s'
      views:
        | never
    }
    'pages/posts/biochemistry-i.md': {
      routes:
        | '/posts/biochemistry-i'
      views:
        | never
    }
    'pages/posts/blind-jb-write-sept-1.md': {
      routes:
        | '/posts/blind-jb-write-sept-1'
      views:
        | never
    }
    'pages/posts/casio-999-01.md': {
      routes:
        | '/posts/casio-999-01'
      views:
        | never
    }
    'pages/posts/casio-999-02.md': {
      routes:
        | '/posts/casio-999-02'
      views:
        | never
    }
    'pages/posts/casio-999-03.md': {
      routes:
        | '/posts/casio-999-03'
      views:
        | never
    }
    'pages/posts/celebrate.md': {
      routes:
        | '/posts/celebrate'
      views:
        | never
    }
    'pages/posts/doppler-effect.md': {
      routes:
        | '/posts/doppler-effect'
      views:
        | never
    }
    'pages/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways.md': {
      routes:
        | '/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways'
      views:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
    }
    'pages/posts/hexo.md': {
      routes:
        | '/posts/hexo'
      views:
        | never
    }
    'pages/posts/how-to-make-an-open-source-dial.md': {
      routes:
        | '/posts/how-to-make-an-open-source-dial'
      views:
        | never
    }
    'pages/posts/memo-protein-folding.md': {
      routes:
        | '/posts/memo-protein-folding'
      views:
        | never
    }
    'pages/posts/openjudge-7940.md': {
      routes:
        | '/posts/openjudge-7940'
      views:
        | never
    }
    'pages/posts/penguinplayer.md': {
      routes:
        | '/posts/penguinplayer'
      views:
        | never
    }
    'pages/posts/phys-note-2122-t1w2.md': {
      routes:
        | '/posts/phys-note-2122-t1w2'
      views:
        | never
    }
    'pages/posts/raspberry-pi-cups-wireless-printer.md': {
      routes:
        | '/posts/raspberry-pi-cups-wireless-printer'
      views:
        | never
    }
    'pages/posts/smartphone-sensor-magfield.md': {
      routes:
        | '/posts/smartphone-sensor-magfield'
      views:
        | never
    }
    'pages/posts/the-way-of-university.md': {
      routes:
        | '/posts/the-way-of-university'
      views:
        | never
    }
    'pages/posts/tijie-p1085.md': {
      routes:
        | '/posts/tijie-p1085'
      views:
        | never
    }
    'pages/posts/tijie-p4414.md': {
      routes:
        | '/posts/tijie-p4414'
      views:
        | never
    }
    'pages/posts/tijie-p5716.md': {
      routes:
        | '/posts/tijie-p5716'
      views:
        | never
    }
    'pages/posts/travel-lights.md': {
      routes:
        | '/posts/travel-lights'
      views:
        | never
    }
    'pages/posts/vscode-cpp.md': {
      routes:
        | '/posts/vscode-cpp'
      views:
        | never
    }
    'pages/posts/wechat-miniapp-token.md': {
      routes:
        | '/posts/wechat-miniapp-token'
      views:
        | never
    }
    'pages/posts/when-a-shoeshine-boy-starts-to-cultivate-lobsters.md': {
      routes:
        | '/posts/when-a-shoeshine-boy-starts-to-cultivate-lobsters'
      views:
        | never
    }
    'pages/posts/wintervacation-plan.md': {
      routes:
        | '/posts/wintervacation-plan'
      views:
        | never
    }
    'pages/posts/yun.md': {
      routes:
        | '/posts/yun'
      views:
        | never
    }
    'pages/random/index.md': {
      routes:
        | '/random/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
