/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/b707o/': RouteRecordInfo<'/b707o/', '/b707o', Record<never, never>, Record<never, never>>,
    '/bullshit-talker/': RouteRecordInfo<'/bullshit-talker/', '/bullshit-talker', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/pomodoro/README': RouteRecordInfo<'/pomodoro/README', '/pomodoro/README', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/9-000-Man-made-Things-Flying-in-Space': RouteRecordInfo<'/posts/9-000-Man-made-Things-Flying-in-Space', '/posts/9-000-Man-made-Things-Flying-in-Space', Record<never, never>, Record<never, never>>,
    '/posts/常见的追击相遇问题及解决策略': RouteRecordInfo<'/posts/常见的追击相遇问题及解决策略', '/posts/常见的追击相遇问题及解决策略', Record<never, never>, Record<never, never>>,
    '/posts/传送带问题及解决策略': RouteRecordInfo<'/posts/传送带问题及解决策略', '/posts/传送带问题及解决策略', Record<never, never>, Record<never, never>>,
    '/posts/运动学': RouteRecordInfo<'/posts/运动学', '/posts/运动学', Record<never, never>, Record<never, never>>,
    '/posts/ai-painting': RouteRecordInfo<'/posts/ai-painting', '/posts/ai-painting', Record<never, never>, Record<never, never>>,
    '/posts/album-stars': RouteRecordInfo<'/posts/album-stars', '/posts/album-stars', Record<never, never>, Record<never, never>>,
    '/posts/apple-love-and-hate-s': RouteRecordInfo<'/posts/apple-love-and-hate-s', '/posts/apple-love-and-hate-s', Record<never, never>, Record<never, never>>,
    '/posts/biochemistry-i': RouteRecordInfo<'/posts/biochemistry-i', '/posts/biochemistry-i', Record<never, never>, Record<never, never>>,
    '/posts/blind-jb-write-sept-1': RouteRecordInfo<'/posts/blind-jb-write-sept-1', '/posts/blind-jb-write-sept-1', Record<never, never>, Record<never, never>>,
    '/posts/casio-999-01': RouteRecordInfo<'/posts/casio-999-01', '/posts/casio-999-01', Record<never, never>, Record<never, never>>,
    '/posts/casio-999-02': RouteRecordInfo<'/posts/casio-999-02', '/posts/casio-999-02', Record<never, never>, Record<never, never>>,
    '/posts/casio-999-03': RouteRecordInfo<'/posts/casio-999-03', '/posts/casio-999-03', Record<never, never>, Record<never, never>>,
    '/posts/celebrate': RouteRecordInfo<'/posts/celebrate', '/posts/celebrate', Record<never, never>, Record<never, never>>,
    '/posts/doppler-effect': RouteRecordInfo<'/posts/doppler-effect', '/posts/doppler-effect', Record<never, never>, Record<never, never>>,
    '/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways': RouteRecordInfo<'/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways', '/posts/draw-ellipse-with-a-mecanum-wheeled-car-in-3-ways', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hexo': RouteRecordInfo<'/posts/hexo', '/posts/hexo', Record<never, never>, Record<never, never>>,
    '/posts/how-to-make-an-open-source-dial': RouteRecordInfo<'/posts/how-to-make-an-open-source-dial', '/posts/how-to-make-an-open-source-dial', Record<never, never>, Record<never, never>>,
    '/posts/openjudge-7940': RouteRecordInfo<'/posts/openjudge-7940', '/posts/openjudge-7940', Record<never, never>, Record<never, never>>,
    '/posts/penguinplayer': RouteRecordInfo<'/posts/penguinplayer', '/posts/penguinplayer', Record<never, never>, Record<never, never>>,
    '/posts/phys-note-2122-t1w2': RouteRecordInfo<'/posts/phys-note-2122-t1w2', '/posts/phys-note-2122-t1w2', Record<never, never>, Record<never, never>>,
    '/posts/raspberry-pi-cups-wireless-printer': RouteRecordInfo<'/posts/raspberry-pi-cups-wireless-printer', '/posts/raspberry-pi-cups-wireless-printer', Record<never, never>, Record<never, never>>,
    '/posts/tijie-p1085': RouteRecordInfo<'/posts/tijie-p1085', '/posts/tijie-p1085', Record<never, never>, Record<never, never>>,
    '/posts/tijie-p4414': RouteRecordInfo<'/posts/tijie-p4414', '/posts/tijie-p4414', Record<never, never>, Record<never, never>>,
    '/posts/tijie-p5716': RouteRecordInfo<'/posts/tijie-p5716', '/posts/tijie-p5716', Record<never, never>, Record<never, never>>,
    '/posts/vscode-cpp': RouteRecordInfo<'/posts/vscode-cpp', '/posts/vscode-cpp', Record<never, never>, Record<never, never>>,
    '/posts/wechat-miniapp-token': RouteRecordInfo<'/posts/wechat-miniapp-token', '/posts/wechat-miniapp-token', Record<never, never>, Record<never, never>>,
    '/posts/wintervacation-plan': RouteRecordInfo<'/posts/wintervacation-plan', '/posts/wintervacation-plan', Record<never, never>, Record<never, never>>,
    '/posts/yun': RouteRecordInfo<'/posts/yun', '/posts/yun', Record<never, never>, Record<never, never>>,
    '/random/': RouteRecordInfo<'/random/', '/random', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
